- dodo.py
- environment-dev.yml
- tools/build.py
- tools/conda_downloads.py
- tools/template.html
Creating a conda downloads badge.
> Setting up conda_download badges [build:website_dev]

- tools/build.py
- tools/conda_downloads.py
Rendered at https://pyviz-dev.github.io/website/tools.html
> Make pypi downloads badge monthly

- README.md
- doc/tutorials/index.rst
- tools/README.md
Trying to capture any special knowledge that I have of the build process.
> Adding docs and fixing tutorial sidebar

- tools/tools.yml
Suggested by @AllenDowney; thanks!
> Added GeoPandas

- tools/conda_downloads.py
- tools/tools.yml
@thewtex these are the changes that you were talking about right?
> Fixing itkwidgets pypi and conda name, also vtk conda_downloads

- .travis.yml
After failure on https://travis-ci.org/pyviz/website/jobs/560016110
> Switching to 3.7

- tools/tools.yml
> Added mpl-scatter-density to list of tools

- doc/overviews/index.md
- tools/tools.yml
> Added Python Grids

- doc/index.md
- tools/tools.yml
(Mostly just because of recently added tools whose popularity is hard to measure until they are added.)
> Resorted tools by current popularity

- tools/conda_downloads.py
intake.Catalog no longer opens catalog files for intake 0.5.5
> changed intake.Catalog to intake.open_catalog

- environment.yml
TypeError: add_source_parser() positional arguments error in Sphinx v3.0.0
following recommendation https://github.com/sphinx-doc/sphinx/issues/7420 to change m2r to m2r @ git+https://github.com/crossnox/m2r@dev#egg=m2r
> fixed sphinx issue

- tools/tools.yml
Added about "facets", A project under "People+AI Research (PAIR) Initiative"
> New visualization package update

- tools/tools.yml
Would you please add [vtkplotter](https://github.com/marcomusy/vtkplotter) to your tool list? Thanks!!
> adding vtkplotter

- doc/overviews/index.md
- tools/tools.yml
Added CMasher and cmcrameri, plus a few overviews
> More colormaps

- .travis.yml
Looks like travis is trying to push to a repo that doesn't exist.
> Change push target for cache

- doc/overviews/index.md
- tools/template.html
Should fix #104 .
Also adds a new dashboarding article.
> Added permalinks to tool sections

- doc/dashboarding/index.md
- doc/overviews/index.md
Should make them easier for people to find.
Also fixed broken title on one of the overviews.
> Moved dashboarding overviews into the dashboarding page

- tools/tools.yml
> Add conda info for glue

- doc/overviews/index.md
> Add HTML link to diagram talk

- tools/tools.yml
A succinct matplotlib wrapper for making beautiful, publication-quality graphics.
> Added proplot

- tools/tools.yml
I took pity on https://github.com/pyviz/pyviz.org/issues/133, maybe this is all it takes?
> Move biggles to the dormant tools, add prettyplotlib, sort dormant tools

- tools/tools.yml
Added taipy to the Dashboarding tools.
Also updated pyviz->holoviz (no visible change, but avoids redirects).
> Added taipy

- tools/tools.yml
Fixes https://github.com/pyviz/pyviz.org/issues/136
> Add conda bits to shiny for python

- .github/workflows/docs.yml
Committed via https://github.com/asottile/all-repos
> bump checkout action

- doc/overviews/index.md
Added link tohttps://gregorhd.github.io/geospatial-visualisation-in-python/
> Added gregorhd overview

- tools/tools.yml
> Added zen_dash and pynecone

- tools/tools.yml
Added h2oai/nitro, pycob/pyvibe, zauberzeug/nicegui, sansyrox/starfyre, widgetti/reacton, and widgetti/solara, plus koonimaru/omniplot.
> Added lots of new web app tools

- tools/tools.yml
Hey, 
thanks for maintaining this useful page! 
I added EOmaps to the list of geospatial visualization packages. 
- https://github.com/raphaelquast/EOmaps
- https://eomaps.readthedocs.io
> add eomaps to geospatial packages

- tools/tools.yml
Thanks for doing this work, and hope my changes are correct
> Add site and conda to solara and reacton

- LICENSE.txt
For some reason, we never added a license to this site!  Looks like I have more commits than all the other contributors combined, and my guess is that CC-BY is the most appropriate, because the interesting content of this site is about data, not code. But if any prior contributor would prefer a different license, please say so!
> Added CC-BY license

- .github/workflows/docs.yml
The less service accounts, the better!
> No longer use the pyviz-developers service account

- .github/workflows/docs.yml
Arf, I'm not sure this is going to work, but let's see.
> Fix the docs workflow

- .github/workflows/docs.yml
> Fix pushing to git from the docs

- .github/workflows/docs.yml
According to https://github.com/pyviz/pyviz.org/issues/177
> Stop building the dev site

- tools/tools.yml
This PR is intended to add [Marsilea](https://github.com/Marsilea-viz/marsilea) as one of the entries.
> Add Marsilea

- tools/tools.yml
Just to update the availability of Marsilea in conda-forge
> Add conda record for Marsilea

- tools/tools.yml
Following up on https://github.com/pyviz/pyviz.org/pull/186
> Xarray: fix typo and update other location

- doc/dashboarding/index.md
- doc/overviews/index.md
Added new dashboarding tool overview article and updated the dashboarding section.
> New dashboarding overview article

- tools/tools.yml
This PR is intended to add [Great Tables](https://github.com/posit-dev/great-tables) as an entry in the `Other InfoVis` category.
> Add entry for Great Tables
